global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'quickpulse'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']