# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messagequeue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messagequeue.proto',
  package='messagequeue',
  syntax='proto3',
  serialized_options=b'Z\026quickpulse/proto;proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12messagequeue.proto\x12\x0cmessagequeue\"!\n\x0eProduceRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"1\n\x0fProduceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x10\n\x0e\x43onsumeRequest\"1\n\x0f\x43onsumeResponse\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"/\n\rStreamMessage\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xee\x01\n\x0cMessageQueue\x12\x46\n\x07Produce\x12\x1c.messagequeue.ProduceRequest\x1a\x1d.messagequeue.ProduceResponse\x12\x46\n\x07\x43onsume\x12\x1c.messagequeue.ConsumeRequest\x1a\x1d.messagequeue.ConsumeResponse\x12N\n\x0eStreamMessages\x12\x1b.messagequeue.StreamMessage\x1a\x1b.messagequeue.StreamMessage(\x01\x30\x01\x42\x18Z\x16quickpulse/proto;protob\x06proto3'
)




_PRODUCEREQUEST = _descriptor.Descriptor(
  name='ProduceRequest',
  full_name='messagequeue.ProduceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='messagequeue.ProduceRequest.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=69,
)


_PRODUCERESPONSE = _descriptor.Descriptor(
  name='ProduceResponse',
  full_name='messagequeue.ProduceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='messagequeue.ProduceResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='messagequeue.ProduceResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=120,
)


_CONSUMEREQUEST = _descriptor.Descriptor(
  name='ConsumeRequest',
  full_name='messagequeue.ConsumeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=138,
)


_CONSUMERESPONSE = _descriptor.Descriptor(
  name='ConsumeResponse',
  full_name='messagequeue.ConsumeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='messagequeue.ConsumeResponse.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='messagequeue.ConsumeResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=189,
)


_STREAMMESSAGE = _descriptor.Descriptor(
  name='StreamMessage',
  full_name='messagequeue.StreamMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='messagequeue.StreamMessage.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='messagequeue.StreamMessage.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=238,
)

DESCRIPTOR.message_types_by_name['ProduceRequest'] = _PRODUCEREQUEST
DESCRIPTOR.message_types_by_name['ProduceResponse'] = _PRODUCERESPONSE
DESCRIPTOR.message_types_by_name['ConsumeRequest'] = _CONSUMEREQUEST
DESCRIPTOR.message_types_by_name['ConsumeResponse'] = _CONSUMERESPONSE
DESCRIPTOR.message_types_by_name['StreamMessage'] = _STREAMMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProduceRequest = _reflection.GeneratedProtocolMessageType('ProduceRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCEREQUEST,
  '__module__' : 'messagequeue_pb2'
  # @@protoc_insertion_point(class_scope:messagequeue.ProduceRequest)
  })
_sym_db.RegisterMessage(ProduceRequest)

ProduceResponse = _reflection.GeneratedProtocolMessageType('ProduceResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCERESPONSE,
  '__module__' : 'messagequeue_pb2'
  # @@protoc_insertion_point(class_scope:messagequeue.ProduceResponse)
  })
_sym_db.RegisterMessage(ProduceResponse)

ConsumeRequest = _reflection.GeneratedProtocolMessageType('ConsumeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMEREQUEST,
  '__module__' : 'messagequeue_pb2'
  # @@protoc_insertion_point(class_scope:messagequeue.ConsumeRequest)
  })
_sym_db.RegisterMessage(ConsumeRequest)

ConsumeResponse = _reflection.GeneratedProtocolMessageType('ConsumeResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMERESPONSE,
  '__module__' : 'messagequeue_pb2'
  # @@protoc_insertion_point(class_scope:messagequeue.ConsumeResponse)
  })
_sym_db.RegisterMessage(ConsumeResponse)

StreamMessage = _reflection.GeneratedProtocolMessageType('StreamMessage', (_message.Message,), {
  'DESCRIPTOR' : _STREAMMESSAGE,
  '__module__' : 'messagequeue_pb2'
  # @@protoc_insertion_point(class_scope:messagequeue.StreamMessage)
  })
_sym_db.RegisterMessage(StreamMessage)


DESCRIPTOR._options = None

_MESSAGEQUEUE = _descriptor.ServiceDescriptor(
  name='MessageQueue',
  full_name='messagequeue.MessageQueue',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=241,
  serialized_end=479,
  methods=[
  _descriptor.MethodDescriptor(
    name='Produce',
    full_name='messagequeue.MessageQueue.Produce',
    index=0,
    containing_service=None,
    input_type=_PRODUCEREQUEST,
    output_type=_PRODUCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Consume',
    full_name='messagequeue.MessageQueue.Consume',
    index=1,
    containing_service=None,
    input_type=_CONSUMEREQUEST,
    output_type=_CONSUMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamMessages',
    full_name='messagequeue.MessageQueue.StreamMessages',
    index=2,
    containing_service=None,
    input_type=_STREAMMESSAGE,
    output_type=_STREAMMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGEQUEUE)

DESCRIPTOR.services_by_name['MessageQueue'] = _MESSAGEQUEUE

# @@protoc_insertion_point(module_scope)
